version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "oftaylor"
    assignees:
      - "oftaylor"
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Group related dependencies together
    groups:
      oapi-codegen:
        patterns:
          - "github.com/oapi-codegen/*"
      testing:
        patterns:
          - "github.com/stretchr/testify"
          - "*testify*"
      runtime:
        patterns:
          - "github.com/google/*"
          - "github.com/apapsch/*"
    # Allow both direct and indirect dependency updates
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    # Ignore major version updates for stability (can be changed as needed)
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "oftaylor"
    assignees:
      - "oftaylor"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"