// Package obsidian provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package obsidian

const (
	ApiKeyAuthScopes = "apiKeyAuth.Scopes"
)

// Defines values for PatchActiveParamsOperation.
const (
	PatchActiveParamsOperationAppend  PatchActiveParamsOperation = "append"
	PatchActiveParamsOperationPrepend PatchActiveParamsOperation = "prepend"
	PatchActiveParamsOperationReplace PatchActiveParamsOperation = "replace"
)

// Defines values for PatchActiveParamsTargetType.
const (
	PatchActiveParamsTargetTypeBlock       PatchActiveParamsTargetType = "block"
	PatchActiveParamsTargetTypeFrontmatter PatchActiveParamsTargetType = "frontmatter"
	PatchActiveParamsTargetTypeHeading     PatchActiveParamsTargetType = "heading"
)

// Defines values for PatchActiveParamsTrimTargetWhitespace.
const (
	PatchActiveParamsTrimTargetWhitespaceFalse PatchActiveParamsTrimTargetWhitespace = "false"
	PatchActiveParamsTrimTargetWhitespaceTrue  PatchActiveParamsTrimTargetWhitespace = "true"
)

// Defines values for DeletePeriodicPeriodParamsPeriod.
const (
	DeletePeriodicPeriodParamsPeriodDaily     DeletePeriodicPeriodParamsPeriod = "daily"
	DeletePeriodicPeriodParamsPeriodMonthly   DeletePeriodicPeriodParamsPeriod = "monthly"
	DeletePeriodicPeriodParamsPeriodQuarterly DeletePeriodicPeriodParamsPeriod = "quarterly"
	DeletePeriodicPeriodParamsPeriodWeekly    DeletePeriodicPeriodParamsPeriod = "weekly"
	DeletePeriodicPeriodParamsPeriodYearly    DeletePeriodicPeriodParamsPeriod = "yearly"
)

// Defines values for GetPeriodicPeriodParamsPeriod.
const (
	GetPeriodicPeriodParamsPeriodDaily     GetPeriodicPeriodParamsPeriod = "daily"
	GetPeriodicPeriodParamsPeriodMonthly   GetPeriodicPeriodParamsPeriod = "monthly"
	GetPeriodicPeriodParamsPeriodQuarterly GetPeriodicPeriodParamsPeriod = "quarterly"
	GetPeriodicPeriodParamsPeriodWeekly    GetPeriodicPeriodParamsPeriod = "weekly"
	GetPeriodicPeriodParamsPeriodYearly    GetPeriodicPeriodParamsPeriod = "yearly"
)

// Defines values for PatchPeriodicPeriodParamsOperation.
const (
	PatchPeriodicPeriodParamsOperationAppend  PatchPeriodicPeriodParamsOperation = "append"
	PatchPeriodicPeriodParamsOperationPrepend PatchPeriodicPeriodParamsOperation = "prepend"
	PatchPeriodicPeriodParamsOperationReplace PatchPeriodicPeriodParamsOperation = "replace"
)

// Defines values for PatchPeriodicPeriodParamsTargetType.
const (
	PatchPeriodicPeriodParamsTargetTypeBlock       PatchPeriodicPeriodParamsTargetType = "block"
	PatchPeriodicPeriodParamsTargetTypeFrontmatter PatchPeriodicPeriodParamsTargetType = "frontmatter"
	PatchPeriodicPeriodParamsTargetTypeHeading     PatchPeriodicPeriodParamsTargetType = "heading"
)

// Defines values for PatchPeriodicPeriodParamsTrimTargetWhitespace.
const (
	PatchPeriodicPeriodParamsTrimTargetWhitespaceFalse PatchPeriodicPeriodParamsTrimTargetWhitespace = "false"
	PatchPeriodicPeriodParamsTrimTargetWhitespaceTrue  PatchPeriodicPeriodParamsTrimTargetWhitespace = "true"
)

// Defines values for PatchPeriodicPeriodParamsPeriod.
const (
	PatchPeriodicPeriodParamsPeriodDaily     PatchPeriodicPeriodParamsPeriod = "daily"
	PatchPeriodicPeriodParamsPeriodMonthly   PatchPeriodicPeriodParamsPeriod = "monthly"
	PatchPeriodicPeriodParamsPeriodQuarterly PatchPeriodicPeriodParamsPeriod = "quarterly"
	PatchPeriodicPeriodParamsPeriodWeekly    PatchPeriodicPeriodParamsPeriod = "weekly"
	PatchPeriodicPeriodParamsPeriodYearly    PatchPeriodicPeriodParamsPeriod = "yearly"
)

// Defines values for PostPeriodicPeriodParamsPeriod.
const (
	PostPeriodicPeriodParamsPeriodDaily     PostPeriodicPeriodParamsPeriod = "daily"
	PostPeriodicPeriodParamsPeriodMonthly   PostPeriodicPeriodParamsPeriod = "monthly"
	PostPeriodicPeriodParamsPeriodQuarterly PostPeriodicPeriodParamsPeriod = "quarterly"
	PostPeriodicPeriodParamsPeriodWeekly    PostPeriodicPeriodParamsPeriod = "weekly"
	PostPeriodicPeriodParamsPeriodYearly    PostPeriodicPeriodParamsPeriod = "yearly"
)

// Defines values for PutPeriodicPeriodParamsPeriod.
const (
	PutPeriodicPeriodParamsPeriodDaily     PutPeriodicPeriodParamsPeriod = "daily"
	PutPeriodicPeriodParamsPeriodMonthly   PutPeriodicPeriodParamsPeriod = "monthly"
	PutPeriodicPeriodParamsPeriodQuarterly PutPeriodicPeriodParamsPeriod = "quarterly"
	PutPeriodicPeriodParamsPeriodWeekly    PutPeriodicPeriodParamsPeriod = "weekly"
	PutPeriodicPeriodParamsPeriodYearly    PutPeriodicPeriodParamsPeriod = "yearly"
)

// Defines values for DeletePeriodicPeriodYearMonthDayParamsPeriod.
const (
	DeletePeriodicPeriodYearMonthDayParamsPeriodDaily     DeletePeriodicPeriodYearMonthDayParamsPeriod = "daily"
	DeletePeriodicPeriodYearMonthDayParamsPeriodMonthly   DeletePeriodicPeriodYearMonthDayParamsPeriod = "monthly"
	DeletePeriodicPeriodYearMonthDayParamsPeriodQuarterly DeletePeriodicPeriodYearMonthDayParamsPeriod = "quarterly"
	DeletePeriodicPeriodYearMonthDayParamsPeriodWeekly    DeletePeriodicPeriodYearMonthDayParamsPeriod = "weekly"
	DeletePeriodicPeriodYearMonthDayParamsPeriodYearly    DeletePeriodicPeriodYearMonthDayParamsPeriod = "yearly"
)

// Defines values for GetPeriodicPeriodYearMonthDayParamsPeriod.
const (
	GetPeriodicPeriodYearMonthDayParamsPeriodDaily     GetPeriodicPeriodYearMonthDayParamsPeriod = "daily"
	GetPeriodicPeriodYearMonthDayParamsPeriodMonthly   GetPeriodicPeriodYearMonthDayParamsPeriod = "monthly"
	GetPeriodicPeriodYearMonthDayParamsPeriodQuarterly GetPeriodicPeriodYearMonthDayParamsPeriod = "quarterly"
	GetPeriodicPeriodYearMonthDayParamsPeriodWeekly    GetPeriodicPeriodYearMonthDayParamsPeriod = "weekly"
	GetPeriodicPeriodYearMonthDayParamsPeriodYearly    GetPeriodicPeriodYearMonthDayParamsPeriod = "yearly"
)

// Defines values for PatchPeriodicPeriodYearMonthDayParamsOperation.
const (
	PatchPeriodicPeriodYearMonthDayParamsOperationAppend  PatchPeriodicPeriodYearMonthDayParamsOperation = "append"
	PatchPeriodicPeriodYearMonthDayParamsOperationPrepend PatchPeriodicPeriodYearMonthDayParamsOperation = "prepend"
	PatchPeriodicPeriodYearMonthDayParamsOperationReplace PatchPeriodicPeriodYearMonthDayParamsOperation = "replace"
)

// Defines values for PatchPeriodicPeriodYearMonthDayParamsTargetType.
const (
	PatchPeriodicPeriodYearMonthDayParamsTargetTypeBlock       PatchPeriodicPeriodYearMonthDayParamsTargetType = "block"
	PatchPeriodicPeriodYearMonthDayParamsTargetTypeFrontmatter PatchPeriodicPeriodYearMonthDayParamsTargetType = "frontmatter"
	PatchPeriodicPeriodYearMonthDayParamsTargetTypeHeading     PatchPeriodicPeriodYearMonthDayParamsTargetType = "heading"
)

// Defines values for PatchPeriodicPeriodYearMonthDayParamsTrimTargetWhitespace.
const (
	PatchPeriodicPeriodYearMonthDayParamsTrimTargetWhitespaceFalse PatchPeriodicPeriodYearMonthDayParamsTrimTargetWhitespace = "false"
	PatchPeriodicPeriodYearMonthDayParamsTrimTargetWhitespaceTrue  PatchPeriodicPeriodYearMonthDayParamsTrimTargetWhitespace = "true"
)

// Defines values for PatchPeriodicPeriodYearMonthDayParamsPeriod.
const (
	PatchPeriodicPeriodYearMonthDayParamsPeriodDaily     PatchPeriodicPeriodYearMonthDayParamsPeriod = "daily"
	PatchPeriodicPeriodYearMonthDayParamsPeriodMonthly   PatchPeriodicPeriodYearMonthDayParamsPeriod = "monthly"
	PatchPeriodicPeriodYearMonthDayParamsPeriodQuarterly PatchPeriodicPeriodYearMonthDayParamsPeriod = "quarterly"
	PatchPeriodicPeriodYearMonthDayParamsPeriodWeekly    PatchPeriodicPeriodYearMonthDayParamsPeriod = "weekly"
	PatchPeriodicPeriodYearMonthDayParamsPeriodYearly    PatchPeriodicPeriodYearMonthDayParamsPeriod = "yearly"
)

// Defines values for PostPeriodicPeriodYearMonthDayParamsPeriod.
const (
	PostPeriodicPeriodYearMonthDayParamsPeriodDaily     PostPeriodicPeriodYearMonthDayParamsPeriod = "daily"
	PostPeriodicPeriodYearMonthDayParamsPeriodMonthly   PostPeriodicPeriodYearMonthDayParamsPeriod = "monthly"
	PostPeriodicPeriodYearMonthDayParamsPeriodQuarterly PostPeriodicPeriodYearMonthDayParamsPeriod = "quarterly"
	PostPeriodicPeriodYearMonthDayParamsPeriodWeekly    PostPeriodicPeriodYearMonthDayParamsPeriod = "weekly"
	PostPeriodicPeriodYearMonthDayParamsPeriodYearly    PostPeriodicPeriodYearMonthDayParamsPeriod = "yearly"
)

// Defines values for PutPeriodicPeriodYearMonthDayParamsPeriod.
const (
	PutPeriodicPeriodYearMonthDayParamsPeriodDaily     PutPeriodicPeriodYearMonthDayParamsPeriod = "daily"
	PutPeriodicPeriodYearMonthDayParamsPeriodMonthly   PutPeriodicPeriodYearMonthDayParamsPeriod = "monthly"
	PutPeriodicPeriodYearMonthDayParamsPeriodQuarterly PutPeriodicPeriodYearMonthDayParamsPeriod = "quarterly"
	PutPeriodicPeriodYearMonthDayParamsPeriodWeekly    PutPeriodicPeriodYearMonthDayParamsPeriod = "weekly"
	PutPeriodicPeriodYearMonthDayParamsPeriodYearly    PutPeriodicPeriodYearMonthDayParamsPeriod = "yearly"
)

// Defines values for PatchVaultFilenameParamsOperation.
const (
	PatchVaultFilenameParamsOperationAppend  PatchVaultFilenameParamsOperation = "append"
	PatchVaultFilenameParamsOperationPrepend PatchVaultFilenameParamsOperation = "prepend"
	PatchVaultFilenameParamsOperationReplace PatchVaultFilenameParamsOperation = "replace"
)

// Defines values for PatchVaultFilenameParamsTargetType.
const (
	PatchVaultFilenameParamsTargetTypeBlock       PatchVaultFilenameParamsTargetType = "block"
	PatchVaultFilenameParamsTargetTypeFrontmatter PatchVaultFilenameParamsTargetType = "frontmatter"
	PatchVaultFilenameParamsTargetTypeHeading     PatchVaultFilenameParamsTargetType = "heading"
)

// Defines values for PatchVaultFilenameParamsTrimTargetWhitespace.
const (
	PatchVaultFilenameParamsTrimTargetWhitespaceFalse PatchVaultFilenameParamsTrimTargetWhitespace = "false"
	PatchVaultFilenameParamsTrimTargetWhitespaceTrue  PatchVaultFilenameParamsTrimTargetWhitespace = "true"
)

// Error defines model for Error.
type Error struct {
	// ErrorCode A 5-digit error code uniquely identifying this particular type of error.
	ErrorCode *float32 `json:"errorCode,omitempty"`

	// Message Message describing the error.
	Message *string `json:"message,omitempty"`
}

// NoteJson defines model for NoteJson.
type NoteJson struct {
	Content     string                 `json:"content"`
	Frontmatter map[string]interface{} `json:"frontmatter"`
	Path        string                 `json:"path"`
	Stat        struct {
		Ctime float32 `json:"ctime"`
		Mtime float32 `json:"mtime"`
		Size  float32 `json:"size"`
	} `json:"stat"`
	Tags []string `json:"tags"`
}

// PatchActiveJSONBody defines parameters for PatchActive.
type PatchActiveJSONBody = string

// PatchActiveParams defines parameters for PatchActive.
type PatchActiveParams struct {
	// Operation Patch operation to perform
	Operation PatchActiveParamsOperation `json:"Operation"`

	// TargetType Type of target to patch
	TargetType PatchActiveParamsTargetType `json:"Target-Type"`

	// TargetDelimiter Delimiter to use for nested targets (i.e. Headings)
	TargetDelimiter *string `json:"Target-Delimiter,omitempty"`

	// Target Target to patch; this value can be URL-Encoded and *must*
	// be URL-Encoded if it includes non-ASCII characters.
	Target string `json:"Target"`

	// TrimTargetWhitespace Trim whitespace from Target before applying patch?
	TrimTargetWhitespace *PatchActiveParamsTrimTargetWhitespace `json:"Trim-Target-Whitespace,omitempty"`
}

// PatchActiveParamsOperation defines parameters for PatchActive.
type PatchActiveParamsOperation string

// PatchActiveParamsTargetType defines parameters for PatchActive.
type PatchActiveParamsTargetType string

// PatchActiveParamsTrimTargetWhitespace defines parameters for PatchActive.
type PatchActiveParamsTrimTargetWhitespace string

// PostOpenFilenameParams defines parameters for PostOpenFilename.
type PostOpenFilenameParams struct {
	// NewLeaf Open this as a new leaf?
	NewLeaf *bool `form:"newLeaf,omitempty" json:"newLeaf,omitempty"`
}

// DeletePeriodicPeriodParamsPeriod defines parameters for DeletePeriodicPeriod.
type DeletePeriodicPeriodParamsPeriod string

// GetPeriodicPeriodParamsPeriod defines parameters for GetPeriodicPeriod.
type GetPeriodicPeriodParamsPeriod string

// PatchPeriodicPeriodJSONBody defines parameters for PatchPeriodicPeriod.
type PatchPeriodicPeriodJSONBody = string

// PatchPeriodicPeriodParams defines parameters for PatchPeriodicPeriod.
type PatchPeriodicPeriodParams struct {
	// Operation Patch operation to perform
	Operation PatchPeriodicPeriodParamsOperation `json:"Operation"`

	// TargetType Type of target to patch
	TargetType PatchPeriodicPeriodParamsTargetType `json:"Target-Type"`

	// TargetDelimiter Delimiter to use for nested targets (i.e. Headings)
	TargetDelimiter *string `json:"Target-Delimiter,omitempty"`

	// Target Target to patch; this value can be URL-Encoded and *must*
	// be URL-Encoded if it includes non-ASCII characters.
	Target string `json:"Target"`

	// TrimTargetWhitespace Trim whitespace from Target before applying patch?
	TrimTargetWhitespace *PatchPeriodicPeriodParamsTrimTargetWhitespace `json:"Trim-Target-Whitespace,omitempty"`
}

// PatchPeriodicPeriodParamsOperation defines parameters for PatchPeriodicPeriod.
type PatchPeriodicPeriodParamsOperation string

// PatchPeriodicPeriodParamsTargetType defines parameters for PatchPeriodicPeriod.
type PatchPeriodicPeriodParamsTargetType string

// PatchPeriodicPeriodParamsTrimTargetWhitespace defines parameters for PatchPeriodicPeriod.
type PatchPeriodicPeriodParamsTrimTargetWhitespace string

// PatchPeriodicPeriodParamsPeriod defines parameters for PatchPeriodicPeriod.
type PatchPeriodicPeriodParamsPeriod string

// PostPeriodicPeriodParamsPeriod defines parameters for PostPeriodicPeriod.
type PostPeriodicPeriodParamsPeriod string

// PutPeriodicPeriodParamsPeriod defines parameters for PutPeriodicPeriod.
type PutPeriodicPeriodParamsPeriod string

// DeletePeriodicPeriodYearMonthDayParamsPeriod defines parameters for DeletePeriodicPeriodYearMonthDay.
type DeletePeriodicPeriodYearMonthDayParamsPeriod string

// GetPeriodicPeriodYearMonthDayParamsPeriod defines parameters for GetPeriodicPeriodYearMonthDay.
type GetPeriodicPeriodYearMonthDayParamsPeriod string

// PatchPeriodicPeriodYearMonthDayJSONBody defines parameters for PatchPeriodicPeriodYearMonthDay.
type PatchPeriodicPeriodYearMonthDayJSONBody = string

// PatchPeriodicPeriodYearMonthDayParams defines parameters for PatchPeriodicPeriodYearMonthDay.
type PatchPeriodicPeriodYearMonthDayParams struct {
	// Operation Patch operation to perform
	Operation PatchPeriodicPeriodYearMonthDayParamsOperation `json:"Operation"`

	// TargetType Type of target to patch
	TargetType PatchPeriodicPeriodYearMonthDayParamsTargetType `json:"Target-Type"`

	// TargetDelimiter Delimiter to use for nested targets (i.e. Headings)
	TargetDelimiter *string `json:"Target-Delimiter,omitempty"`

	// Target Target to patch; this value can be URL-Encoded and *must*
	// be URL-Encoded if it includes non-ASCII characters.
	Target string `json:"Target"`

	// TrimTargetWhitespace Trim whitespace from Target before applying patch?
	TrimTargetWhitespace *PatchPeriodicPeriodYearMonthDayParamsTrimTargetWhitespace `json:"Trim-Target-Whitespace,omitempty"`
}

// PatchPeriodicPeriodYearMonthDayParamsOperation defines parameters for PatchPeriodicPeriodYearMonthDay.
type PatchPeriodicPeriodYearMonthDayParamsOperation string

// PatchPeriodicPeriodYearMonthDayParamsTargetType defines parameters for PatchPeriodicPeriodYearMonthDay.
type PatchPeriodicPeriodYearMonthDayParamsTargetType string

// PatchPeriodicPeriodYearMonthDayParamsTrimTargetWhitespace defines parameters for PatchPeriodicPeriodYearMonthDay.
type PatchPeriodicPeriodYearMonthDayParamsTrimTargetWhitespace string

// PatchPeriodicPeriodYearMonthDayParamsPeriod defines parameters for PatchPeriodicPeriodYearMonthDay.
type PatchPeriodicPeriodYearMonthDayParamsPeriod string

// PostPeriodicPeriodYearMonthDayParamsPeriod defines parameters for PostPeriodicPeriodYearMonthDay.
type PostPeriodicPeriodYearMonthDayParamsPeriod string

// PutPeriodicPeriodYearMonthDayParamsPeriod defines parameters for PutPeriodicPeriodYearMonthDay.
type PutPeriodicPeriodYearMonthDayParamsPeriod string

// PostSearchApplicationVndOlrapiJSONlogicPlusJSONBody defines parameters for PostSearch.
type PostSearchApplicationVndOlrapiJSONlogicPlusJSONBody = map[string]interface{}

// PostSearchSimpleParams defines parameters for PostSearchSimple.
type PostSearchSimpleParams struct {
	// Query Your search query
	Query string `form:"query" json:"query"`

	// ContextLength How much context to return around the matching string
	ContextLength *float32 `form:"contextLength,omitempty" json:"contextLength,omitempty"`
}

// PatchVaultFilenameJSONBody defines parameters for PatchVaultFilename.
type PatchVaultFilenameJSONBody = string

// PatchVaultFilenameParams defines parameters for PatchVaultFilename.
type PatchVaultFilenameParams struct {
	// Operation Patch operation to perform
	Operation PatchVaultFilenameParamsOperation `json:"Operation"`

	// TargetType Type of target to patch
	TargetType PatchVaultFilenameParamsTargetType `json:"Target-Type"`

	// TargetDelimiter Delimiter to use for nested targets (i.e. Headings)
	TargetDelimiter *string `json:"Target-Delimiter,omitempty"`

	// Target Target to patch; this value can be URL-Encoded and *must*
	// be URL-Encoded if it includes non-ASCII characters.
	Target string `json:"Target"`

	// TrimTargetWhitespace Trim whitespace from Target before applying patch?
	TrimTargetWhitespace *PatchVaultFilenameParamsTrimTargetWhitespace `json:"Trim-Target-Whitespace,omitempty"`
}

// PatchVaultFilenameParamsOperation defines parameters for PatchVaultFilename.
type PatchVaultFilenameParamsOperation string

// PatchVaultFilenameParamsTargetType defines parameters for PatchVaultFilename.
type PatchVaultFilenameParamsTargetType string

// PatchVaultFilenameParamsTrimTargetWhitespace defines parameters for PatchVaultFilename.
type PatchVaultFilenameParamsTrimTargetWhitespace string

// PatchActiveJSONRequestBody defines body for PatchActive for application/json ContentType.
type PatchActiveJSONRequestBody = PatchActiveJSONBody

// PatchPeriodicPeriodJSONRequestBody defines body for PatchPeriodicPeriod for application/json ContentType.
type PatchPeriodicPeriodJSONRequestBody = PatchPeriodicPeriodJSONBody

// PatchPeriodicPeriodYearMonthDayJSONRequestBody defines body for PatchPeriodicPeriodYearMonthDay for application/json ContentType.
type PatchPeriodicPeriodYearMonthDayJSONRequestBody = PatchPeriodicPeriodYearMonthDayJSONBody

// PostSearchApplicationVndOlrapiJSONlogicPlusJSONRequestBody defines body for PostSearch for application/vnd.olrapi.jsonlogic+json ContentType.
type PostSearchApplicationVndOlrapiJSONlogicPlusJSONRequestBody = PostSearchApplicationVndOlrapiJSONlogicPlusJSONBody

// PatchVaultFilenameJSONRequestBody defines body for PatchVaultFilename for application/json ContentType.
type PatchVaultFilenameJSONRequestBody = PatchVaultFilenameJSONBody
